# Site settings
title: Jawad Kazi profile
description: My portfolio for programming and development
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://seebinjwad.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jawad Kazi
user_description: A developer with a background in cs.
user_title: Software Developer
email: kazijawadahmed@gmail.com
twitter_username: kazijawadahmed
github_username:  SeebinJwad
gplus_username:  kazijawadahmed

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
