# Site settings
title: Jawad Kazi profile
description: My portfolio for programming and development
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://seebinjwad.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jawad Kazi
user_description: Hi! My name is Jawad Kazi. I am currently an undergraduate student at UT Austin seeking internships, fellowships, co-op, and other work opportunity in the tech and finance fields. I am an incoming Junior, pursuing a double major in data science mathematics and quantitative economics, certifications in scientific computation and elements of computing, and a minor in Arabic. I was born in Indiana, raised in California and Texas, live with my family in Houston, and go to college in Austin. Outside of university, I am deeply involved in the startup scene in Austin, being the youngest mentor in the US in the largest pre-seed startup accelerator, Founders Institute. This position provides me equity in dozens of startups in the Austin area, in return for my technical expertise, which I gained while working as a freelancer for numerous long term client startups on the Upwork freelance platform. Aside from corporate and startup involvement, I also have a strong interest in research and academia, being a bioinformatic research assistant for the Mitchell J. Frederick Lab of Otolaryngology for the past four summers (and part time assistance remotely during the school year). Through my consistent effort and data science knowledge, I became a co-author in the paper "Evolution of Cisplatin Resistance...", a landmark paper published in Nature, the world's most prestigious peer-reviewed science journal.
user_title: Software + ML/AI Engineer
email: kazijawadahmed@gmail.com
twitter_username: kazijawadahmed
github_username:  SeebinJwad
gplus_username:  kazijawadahmed

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
